services:
    Enhavo\Bundle\UserBundle\Menu\UserMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\UserBundle\Menu\GroupMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\UserBundle\Menu\UserMainMenuType:
        tags:
            - { name: enhavo_app.menu }