enhavo_user_change_password_change:
    path: /change-password
    methods: [ GET, POST ]
    defaults:
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_user_admin_api_change_password
        _endpoint:
            type: admin
