enhavo_user_admin_user_index:
    path: /user/index
    defaults:
        _expose: admin
        _vue:
            component: resource-index
            groups: admin
            meta:
                api: enhavo_user_admin_api_user_index
        _endpoint:
            type: admin

enhavo_user_admin_user_create:
    path: /user/create
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_user_admin_api_user_create
        _endpoint:
            type: admin

enhavo_user_admin_user_update:
    path: '/user/update/{id}'
    defaults:
        _expose: admin
        _vue:
            component: resource-input
            groups: admin
            meta:
                api: enhavo_user_admin_api_user_update
        _endpoint:
            type: admin
