enhavo_user_admin_api_change_password:
    path: /change-password
    methods:
        - GET
        - POST
    defaults:
        _expose: admin_api
        _endpoint:
            type: resource_update
            input: enhavo_user.user.change_password
